### PR TITLE
Update token management and config for unleash v5.x

### PR DESCRIPTION
**Pull request by hemslo**
Update token management and config following:

* [Upgrading Unleash](https://docs.getunleash.io/using-unleash/deploy/upgrading-unleash)
* [Environments migration](https://docs.getunleash.io/reference/environments#migration)
* [Securing Unleash](https://docs.getunleash.io/using-unleash/deploy/securing-unleash)

Main changes:

* `SESSION_SECRET` removed
* `ADMIN_ACCESS_TOKEN` -> `INIT_ADMIN_API_TOKENS`
* `CLIENT_ACCESS_TOKEN` -> `INIT_CLIENT_API_TOKENS`.

[APPSRE-7691](https://issues.redhat.com/browse/APPSRE-7691)

### CODE REVIEW

**Review by janboll — CHANGES_REQUESTED** [review]
Please update pko package as well

**Comment by janboll** [comment]
I totally missed that. Looking good!

**Comment by janboll** [comment]
So, with this change we have to rotate the tokens, is that correct?

**Comment by hemslo** [comment]
> So, with this change we have to rotate the tokens, is that correct?

Yes, the token format changed, have to do a one time token rotate (init in db).

**Pull request merged**
